on:
  push:
    branches:
      - release
jobs:
  build:
    name: Run tests and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run tests
        run: go test -v ./...
      - name: Build binary
        run: go build -v ./...
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: govm
          path: ./govm
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Download govm binary
        uses: actions/download-artifact@v3
        with:
          name: govm
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: govm
